# Q-Learning 
<small> **using numpy** </small>

In [1]:
!pip install gym

    100% |████████████████████████████████| 1.5MB 7.6MB/s 
    100% |████████████████████████████████| 1.0MB 11.2MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /root/.cache/pip/wheels/6c/3a/0e/b86dee98876bb56cdb482cc1f72201035e46d1baf69d10d028
Successfully built gym


In [0]:
import gym
import numpy as np
import time

In [3]:
# Create the env
env = gym.make('FrozenLake-v0')

/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [0]:
# Getting the action space and state space
action_size = env.action_space.n
state_size = env.observation_space.n

In [5]:
# Initializing the Q-table with zeros
qtable = np.zeros((state_size, action_size))
print (qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
# Specify the hyperparameters
episodes = 20000
lr = 0.8
max_steps = 99
gamma = 0.95

# Exploration Parameters

## Exploration rate
epsilon = 1.0

## Exploration probability at start
max_epsilon = 1.0

## Minimum exploration probability
min_epsilon = 0.01

## Decay rate for exploration
decay_rate = 0.005

<img src='https://github.com/iArunava/Q-Learning/blob/master/assets/qtable_algo.png?raw=1' />

In [37]:
# Implement the Q-Learning Algorithm
rewards = []

#2
for episode in range(episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    start = time.time()
    
    for step in range(max_steps):
        #3
        exp_exp_tradeoff = np.random.uniform(0, 1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
        
        #4
        # Take the action
        new_state, reward, done, info = env.step(action)
        
        #5
        # Update Q(s, a) := Q(s, a) + lr[R(s, a) + gamma * max Q(s`, a`) - Q(s, a)]
        qtable[state, action] = qtable[state, action] + lr \
                                * (reward + (gamma * np.max(qtable[new_state, :])) \
                                - qtable[state, action])
        
        #print (reward, epsilon)
        total_rewards += reward
        
        state = new_state
        
        if done:
            break
    
    end = time.time()
    
    # Reduce epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)
    
    #print ('Episode: {}/{} | Rewards: {:.3f} | Time taken: {:.3f}'
    #        .format(episode+1, episodes, total_rewards, (end-start)))
    
print ('Agent Trained Successfully!!')
print ('Rewards over time: {:.3f}'.format(sum(rewards) / episodes))
            

Agent Trained Successfully!!
Rewards over time: 0.495


In [29]:
qtable

array([[9.26621699e-02, 5.42873780e-02, 2.44208824e-02, 6.23859391e-02],
       [5.46661889e-03, 4.66084645e-03, 1.02101386e-02, 6.44900402e-02],
       [4.77152932e-03, 4.68749935e-03, 8.50547401e-03, 5.10734453e-02],
       [3.10981617e-03, 2.09999100e-04, 1.66867498e-03, 3.27656119e-02],
       [1.60550002e-01, 3.26512840e-02, 2.57688882e-02, 9.31344766e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.25319529e-05, 2.07313769e-04, 5.74040035e-02, 1.41594589e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.77030304e-02, 7.24366663e-04, 2.60690062e-02, 2.75082725e-01],
       [6.73103373e-04, 2.90987847e-01, 3.04447035e-02, 1.26541657e-02],
       [1.77090576e-01, 1.01038374e-03, 1.30240987e-05, 2.52105386e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.02489228e-01, 2.23222021e-02, 2.93832350e

In [36]:
# Use the Q-Table to play

env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print ('******************************************')
    print ('Episode ', episode)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done or step == max_steps:
            env.render()
            print ('Number of steps: {}'.format(step+1))
            break
            
        state = new_state
        
env.close()

******************************************
Episode  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps: 75
******************************************
Episode  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps: 12
******************************************
Episode  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps: 11
******************************************
Episode  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps: 28
******************************************
Episode  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps: 58
